#!/usr/bin/env bash
set -eo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Downloads a video audio in the current directory
##?
##? Usage:
##?   download-mp3 <url>

yt-dlp -x -f bestaudio --audio-format flac --embed-metadata --embed-thumbnail "$1"
