#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Normalize cover images in a directory
#?? 1.0.0
##?
##? Usage:
##?   normalize_cover <directory>
##?
docs::parse "$@"

# Carpeta donde está este script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
VENV_DIR="$SCRIPT_DIR/python/.venv"
PY_SCRIPT="$SCRIPT_DIR/python/normalize_cover.py"

if [ "$#" -ne 1 ]; then
  echo "$# argumentos proporcionados, se esperaba 1."
  echo "Uso: $0 /ruta/a/la/carpeta"
  exit 1
fi

TARGET_DIR="$1"

if [ ! -d "$TARGET_DIR" ]; then
  echo "❌ Ruta inválida: $TARGET_DIR"
  exit 1
fi

if [ ! -d "$VENV_DIR" ]; then
  echo "🛠 Creando virtual environment en $VENV_DIR ..."
  python3 -m venv "$VENV_DIR"
fi

# Activar venv
source "$VENV_DIR/bin/activate"

# Instalar dependencias si no están
pip install --quiet --disable-pip-version-check eyed3 Pillow

# Ejecutar script python con path absoluto
python3 "$PY_SCRIPT" "$TARGET_DIR"
