#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show the wifi password on Mac
##? Keychain password is required
#?? 1.0.0
##?
##? Usage:
##?   wifi_password
docs::parse "$@"

wifi_interface=$(networksetup -listallhardwareports | awk '/Wi-Fi|Airport/{getline; print $NF}')

wifi_ssid=$(networksetup -getairportnetwork "$wifi_interface" | awk -F': ' '{print $2}')

wifi_password=$(security find-generic-password -wa "$wifi_ssid")

echo "$wifi_ssid"
echo "$wifi_password"
